version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: cop-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    container_name: cop-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
